### ISSUE TITLE
刷Meterey，蓝牙不能用

### ISSUE THREAD

**Issue by Flowers-xin** [978025302/Hackintosh-HP-ProDesk-400G2-Mini-EFI#2]
老哥咱们配置一样，刷Meterey，蓝牙不能用，用的你的EFI OC 7.7，请教一下

**Comment by QAQstar** [comment]
蓝牙是打不开吗，还是能打开只是连不上蓝牙设备？网卡型号也和我的一样吗？如果一样的话可以尝试完全断电后再开机试试。以及我没有更新到最新的Monterey，因为机子现在不在我手上，因为疫情原因我也没办法拿到机子更新系统。。

**Comment by Flowers-xin** [comment]
- [ ] @978025302 我怀疑可能是网卡问题，我的不是653开头的网卡。![image](https://user-images.githubusercontent.com/77136636/163539899-32f75863-3a33-42a9-a7f1-d5561292f395.png)

**Comment by QAQstar** [comment]
那好像Monterey下确实不太行

**Comment by Flowers-xin** [comment]
重新换了个网卡，等到了试试吧。感谢老哥分享的EFI
