### ISSUE TITLE
有打算更新尝鲜beat版吗？

### ISSUE THREAD

**Issue by ghost** [978025302/Hackintosh-HP-ProDesk-400G2-Mini-EFI#4]
有打算更新尝鲜beat版吗？

**Comment by QAQstar** [comment]
周末可能会试试，现在OpenCore已经更新到0.8.1了，我也同步更新了下，如果用下来问题不大就传上来

**Comment by hcb8174875** [comment]
请问版主知道400g2支持6400标压处理器吗？这个处理器可以用您这个EFI文件吗

**Comment by 978025302** [comment]
> 

理论上可以，但是散热可能撑不住

**Comment by QAQstar** [comment]
> 请问版主知道400g2支持6400标压处理器吗？这个处理器可以用您这个EFI文件吗

理论上可以，但是散热可能撑不住

**Comment by hcb8174875** [comment]
好滴，谢谢，我打算买个400g2试试，到时候上个好一点的硅脂。主要是手里有两块拆机下来的6400，组个小主机放客厅看电视用
